### ISSUE TITLE
Logo/Icon For DSC Movie Listing App

### ISSUE THREAD

**Issue by zularizal** [rakhi2104/DSC-MovieListingApp#2]
Hi @rakhi2104 , I am a graphic designer, I want to help you in graphic design.

After I review your project, your app is very good but this app does not yet have a logo. Therefore I suggest a logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by rakhi2104** [comment]
Thanks for considering, But this was made only for a Workshop which was organized in our college.
Thanks again. :+1: 
Btw, I'm also a Graphic Designer. :yum:
